Highcharts.chart("chart7", {
    chart: {
        type: "packedbubble",
        height: "100%",
    },


    tooltip: {
        useHTML: true,
        pointFormat: "<b>{point.name}:</b> {point.y} mtCO<sub>2</sub>e",
    },
    plotOptions: {
        packedbubble: {
            minSize: "30%",
            maxSize: "120%",
            zMin: 0,
            zMax: 1000,
            layoutAlgorithm: {
                gravitationalConstant: 0.05,
                splitSeries: true,
                seriesInteraction: false,
                dragBetweenSeries: true,
                parentNodeLimit: true,
            },
            dataLabels: {
                enabled: true,
                format: "{point.name}",
                filter: {
                    property: "y",
                    operator: ">",
                    value: 250,
                },
                style: {
                    color: "black",
                    textOutline: "none",
                    fontWeight: "normal",
                },
            },
        },
    },
    series: [
        {
            name: "欧洲",
            data: [
                { name: "Croatia", value: 2 },
                { name: "Belgium", value: 12.18 },
                { name: "Czech Republic", value: 93.17 },
                { name: "Netherlands", value: 90.47 },
                { name: "Spain", value: 147.7 },
                { name: "Ukraine", value: 226.09 },
                { name: "Poland", value: 162.54 },
                { name: "France", value: 262.22 },
                { name: "Romania", value: 238.53 },
                { name: "United Kingdom", value: 51.06 },
                { name: "Turkey", value: 337.96 },
                { name: "Italy", value: 368.19 },
                { name: "Greece", value: 304.42 },
                { name: "Austria", value: 61.39 },
                { name: "Belarus", value: 57.64 },
                { name: "Serbia", value: 36.16 },
                { name: "Finland", value: 45.86 },
                { name: "Bulgaria", value: 47.65 },
                { name: "Portugal", value: 5.34 },
                { name: "Norway", value: 44.93 },
                { name: "Sweden", value: 17.02 },
                { name: "Hungary", value: 18.69 },
                { name: "Switzerland", value: 48.27 },
                { name: "Denmark", value: 35.14 },
                { name: "Slovakia", value: 30.55 },
                { name: "Ireland", value: 30.01 },
                { name: "Croatia", value: 32.96 },
                { name: "Estonia", value: 12.18 },
                { name: "Slovenia", value: 12.13 },
                { name: "Lithuania", value: 13.94 },
                { name: "Luxembourg", value: 11.1 },
                { name: "Macedonia", value: 9.21 },
                { name: "Moldova", value: 8.3 },
                { name: "Latvia", value: 8.97 },
                { name: "Cyprus", value: 4.79 },
            ],
        },
        {
            name: "非洲",
            data: [
                { name: "Senegal", value: 6.94 },
                { name: "Cameroon", value: 14.95 },
                { name: "Zimbabwe", value: 43.19 },
                { name: "Ghana", value: 98.92 },
                { name: "Kenya", value: -4.88 },
                { name: "Sudan", value: 14.66 },
                { name: "Tunisia", value: 41.63 },
                { name: "Angola", value: 26.12 },
                { name: "Libya", value: 60.8 },
                { name: "Morocco", value: 56.8 },
                { name: "Ethiopia", value: 69.54 },
                { name: "Nigeria", value: 50.07 },
                { name: "South Africa", value: 161.27 },
                { name: "Egypt", value: 446.19 },
                { name: "Algeria", value: 249.55 },
            ],
        },
        {
            name: "大洋洲",
            data: [
                { name: "Australia", value: 171.45 },
                { name: "New Zealand", value: 388.71 },
            ],
        },
        {
            name: "北美洲",
            data: [
                { name: "Costa Rica", value: 23.39 },
                { name: "Honduras", value: 0.94 },
                { name: "Jamaica", value: 15.74 },
                { name: "Panama", value: 8.57 },
                { name: "Guatemala", value: 17.74 },
                { name: "Cuba", value: 22.58 },
                { name: "USA", value: 22.86 },
                { name: "Canada", value: 4585.99 },
                { name: "Mexico", value: 615.48 },
            ],
        },
        {
            name: "南美洲",
            data: [
                { name: "El Salvador", value: 463.71 },
                { name: "Uruguay", value: 8.88 },
                { name: "Bolivia", value: 4.72 },
                { name: "Ecuador", value: 89.72 },
                { name: "Chile", value: 65.44 },
                { name: "Peru", value: 33.51 },
                { name: "Colombia", value: 146.54 },
                { name: "Brazil", value: 164.01 },
                { name: "Argentina", value: 818.6 },
                { name: "Venezuela", value: 197.8 },
            ],
        },
        {
            name: "亚洲",
            data: [
                { name: "Nepal", value: 155.47 },
                { name: "Georgia", value: 16.39 },
                { name: "Kyrgyzstan", value: 10.11 },
                { name: "Afghanistan", value: 6.78 },
                { name: "Myanmar", value: 6.23 },
                { name: "Mongolia", value: 139.37 },
                { name: "Sri Lanka", value: 26.17 },
                { name: "Bahrain", value: 25.69 },
                { name: "Yemen", value: 33.25 },
                { name: "Jordan", value: 11.1 },
                { name: "Lebanon", value: 24.63 },
                { name: "Azerbaijan", value: 27.87 },
                { name: "Singapore", value: 33.59 },
                { name: "Syria", value: 47.41 },
                { name: "North Korea", value: 25.72 },
                { name: "Israel", value: 59.33 },
                { name: "Turkmenistan", value: 62.73 },
                { name: "Oman", value: 72.87 },
                { name: "Qatar", value: 76.05 },
                { name: "Philippines", value: 91.97 },
                { name: "Kuwait", value: 147.88 },
                { name: "Uzbekistan", value: 92.65 },
                { name: "Iraq", value: 113.34 },
                { name: "Pakistan", value: 175.05 },
                { name: "Vietnam", value: 197.57 },
                { name: "Malaysia", value: 324.0 },
                { name: "Kazakhstan", value: 334.48 },
                { name: "Thailand", value: 209.12 },
                { name: "Indonesia", value: 280.13 },
                { name: "Saudi Arabia", value: 1475.21 },
                { name: "Japan", value: 523.78 },
                { name: "China", value: 1049.5 },
                { name: "India", value: 10057.12 },
                { name: "Russia", value: 2422.03 },
                { name: "Iran", value: 1145.09 },
                { name: "South Korea", value: 630.07 },
            ],
        },
    ],
});