<<<<<<< HEAD
var chart_chart14 = echarts.init(
    document.getElementById("chart14"),
    "white",
    { renderer: "canvas" }
);
var option_chart14 = {
    animation: true,
    animationThreshold: 2000,
    animationDuration: 1000,
    animationEasing: "cubicOut",
    animationDelay: 0,
    animationDurationUpdate: 300,
    animationEasingUpdate: "cubicOut",
    animationDelayUpdate: 0,
    grid: {
        left: "2%",
        right: "2%",
        top: "15%",
        containLabel: true,
      },

    color: [
        "#5793f3",
        "#c23531",
        "#2f4554",
        "#61a0a8",
        "#d48265",
        "#749f83",
        "#ca8622",
        "#bda29a",
        "#6e7074",
        "#546570",
        "#c4ccd3",
        "#f05b72",
        "#ef5b9c",
        "#f47920",
        "#905a3d",
        "#fab27b",
        "#2a5caa",
        "#444693",
        "#726930",
        "#b2d235",
        "#6d8346",
        "#ac6767",
        "#1d953f",
        "#6950a1",
        "#918597",
        "#1AA034",
    ],
    series: [
        {
            type: "bar",
            name: "\u9500\u91cf",
            yAxisIndex: 0,
            legendHoverLink: true,
            data: [126, 121, 130, 180, 230, 303, 401, 530],
            showBackground: false,
            barMinHeight: 0,
            barCategoryGap: "20%",
            barGap: "30%",
            large: false,
            largeThreshold: 400,
            seriesLayoutBy: "column",
            datasetIndex: 0,
            clip: true,
            zlevel: 0,
            z: 2,
            color: "#1AA034",
            label: {
                show: true,
                position: "inside",
                margin: 8,
                fontSize: 12,
            },
        },
        {
            type: "line",
            name: "\u65b0\u80fd\u6e90\u6c7d\u8f66\u5360\u6c7d\u8f66\u9500\u91cf\u6bd4\u4f8b",
            connectNulls: false,
            yAxisIndex: 2,
            symbolSize: 4,
            showSymbol: true,
            smooth: false,
            clip: true,
            step: false,
            color: "#d14a61",
            data: [
                ["2018", 4.5],
                ["2019", 4.7],
                ["2020", 5.2],
                ["2021", 6.8],
                ["2022", 8.9],
                ["2023", 11.7],
                ["2024", 15.3],
                ["2025", 20.0],
            ],
            hoverAnimation: true,
            label: {
                show: true,
                position: "top",
                margin: 8,
                fontSize: 15,
            },
            lineStyle: {
                show: true,
                width: 1,
                opacity: 1,
                curveness: 0,
                type: "solid",
            },
            areaStyle: {
                opacity: 0,
            },
            zlevel: 0,
            z: 0,
        },
    ],
    legend: [
        {
            data: [
                "\u9500\u91cf",
                "\u65b0\u80fd\u6e90\u6c7d\u8f66\u5360\u6c7d\u8f66\u9500\u91cf\u6bd4\u4f8b",
            ],
            selected: {
                "\u9500\u91cf": true,
                "\u65b0\u80fd\u6e90\u6c7d\u8f66\u5360\u6c7d\u8f66\u9500\u91cf\u6bd4\u4f8b": true,
            },
            show: true,
            padding: 50,
            itemGap: 10,
            itemWidth: 25,
            itemHeight: 14,
        },
    ],
    tooltip: {
        show: true,
        trigger: "axis",
        triggerOn: "mousemove|click",
        axisPointer: {
            type: "cross",
        },
        showContent: true,
        alwaysShowContent: false,
        showDelay: 0,
        hideDelay: 100,
        textStyle: {
            fontSize: 14,
        },
        borderWidth: 0,
        padding: 5,
    },
    xAxis: [
        {
            show: true,
            scale: false,
            nameLocation: "end",
            nameGap: 15,
            gridIndex: 0,
            inverse: false,
            offset: 0,
            splitNumber: 5,
            minInterval: 0,
            splitLine: {
                show: false,
                lineStyle: {
                    show: true,
                    width: 1,
                    opacity: 1,
                    curveness: 0,
                    type: "solid",
                },
            },
            data: [
                "2018",
                "2019",
                "2020",
                "2021",
                "2022",
                "2023",
                "2024",
                "2025",
            ],
        },
    ],
    yAxis: [
        {
            show: true,
            scale: false,
            nameLocation: "end",
            nameGap: 15,
            gridIndex: 0,
            inverse: false,
            offset: 0,
            splitNumber: 5,
            minInterval: 0,
            splitLine: {
                show: false,
                lineStyle: {
                    show: true,
                    width: 1,
                    opacity: 1,
                    curveness: 0,
                    type: "solid",
                },
            },
        },
        {
            type: "value",
            name: "\u9500\u91cf\uff08\u4e07\u8f86\uff09",
            show: true,
            scale: false,
            nameLocation: "end",
            nameGap: 15,
            gridIndex: 0,
            axisLine: {
                show: true,
                onZero: true,
                onZeroAxisIndex: 0,
                lineStyle: {
                    show: true,
                    width: 1,
                    opacity: 1,
                    curveness: 0,
                    type: "solid",
                    color: "black",
                },
            },
            axisLabel: {
                show: true,
                position: "top",
                margin: 8,
                formatter: "{value}",
            },
            inverse: false,
            position: "left",
            offset: 0,
            splitNumber: 5,
            min: 0,
            max: 600,
            minInterval: 0,
            splitLine: {
                show: false,
                lineStyle: {
                    show: true,
                    width: 1,
                    opacity: 1,
                    curveness: 0,
                    type: "solid",
                },
            },
        },
        {
            type: "value",
            name: "\u767e\u5206\u6bd4",
            show: true,
            scale: false,
            nameLocation: "end",
            nameGap: 15,
            gridIndex: 0,
            axisLine: {
                show: true,
                onZero: true,
                onZeroAxisIndex: 0,
                lineStyle: {
                    show: true,
                    width: 1,
                    opacity: 1,
                    curveness: 0,
                    type: "solid",
                    color: "#d14a61",
                },
            },
            axisLabel: {
                show: true,
                position: "top",
                margin: 8,
                formatter: "{value} %",
            },
            inverse: false,
            position: "right",
            offset: 0,
            splitNumber: 5,
            min: 0,
            max: 20,
            minInterval: 0,
            splitLine: {
                show: true,
                lineStyle: {
                    show: true,
                    width: 1,
                    opacity: 1,
                    curveness: 0,
                    type: "solid",
                },
            },
        },
    ],
    title: [
        {
            text: "新能源汽车销量及占比",
            x: "center",
            y: "top",
            textStyle: {
                fontSize: 30,
                color: "black",
                itemGap: 10,
            },
        },
    ],
};
chart_chart14.setOption(
    option_chart14
=======
var chart_chart14 = echarts.init(
    document.getElementById("chart14"),
    "white",
    { renderer: "canvas" }
);
var option_chart14 = {
    animation: true,
    animationThreshold: 2000,
    animationDuration: 1000,
    animationEasing: "cubicOut",
    animationDelay: 0,
    animationDurationUpdate: 300,
    animationEasingUpdate: "cubicOut",
    animationDelayUpdate: 0,
    grid: {
        left: "2%",
        right: "2%",
        top: "15%",
        containLabel: true,
      },

    color: [
        "#5793f3",
        "#c23531",
        "#2f4554",
        "#61a0a8",
        "#d48265",
        "#749f83",
        "#ca8622",
        "#bda29a",
        "#6e7074",
        "#546570",
        "#c4ccd3",
        "#f05b72",
        "#ef5b9c",
        "#f47920",
        "#905a3d",
        "#fab27b",
        "#2a5caa",
        "#444693",
        "#726930",
        "#b2d235",
        "#6d8346",
        "#ac6767",
        "#1d953f",
        "#6950a1",
        "#918597",
        "#1AA034",
    ],
    series: [
        {
            type: "bar",
            name: "\u9500\u91cf",
            yAxisIndex: 0,
            legendHoverLink: true,
            data: [126, 121, 130, 180, 230, 303, 401, 530],
            showBackground: false,
            barMinHeight: 0,
            barCategoryGap: "20%",
            barGap: "30%",
            large: false,
            largeThreshold: 400,
            seriesLayoutBy: "column",
            datasetIndex: 0,
            clip: true,
            zlevel: 0,
            z: 2,
            color: "#1AA034",
            label: {
                show: true,
                position: "inside",
                margin: 8,
                fontSize: 12,
            },
        },
        {
            type: "line",
            name: "\u65b0\u80fd\u6e90\u6c7d\u8f66\u5360\u6c7d\u8f66\u9500\u91cf\u6bd4\u4f8b",
            connectNulls: false,
            yAxisIndex: 2,
            symbolSize: 4,
            showSymbol: true,
            smooth: false,
            clip: true,
            step: false,
            color: "#d14a61",
            data: [
                ["2018", 4.5],
                ["2019", 4.7],
                ["2020", 5.2],
                ["2021", 6.8],
                ["2022", 8.9],
                ["2023", 11.7],
                ["2024", 15.3],
                ["2025", 20.0],
            ],
            hoverAnimation: true,
            label: {
                show: true,
                position: "top",
                margin: 8,
                fontSize: 15,
            },
            lineStyle: {
                show: true,
                width: 1,
                opacity: 1,
                curveness: 0,
                type: "solid",
            },
            areaStyle: {
                opacity: 0,
            },
            zlevel: 0,
            z: 0,
        },
    ],
    legend: [
        {
            data: [
                "\u9500\u91cf",
                "\u65b0\u80fd\u6e90\u6c7d\u8f66\u5360\u6c7d\u8f66\u9500\u91cf\u6bd4\u4f8b",
            ],
            selected: {
                "\u9500\u91cf": true,
                "\u65b0\u80fd\u6e90\u6c7d\u8f66\u5360\u6c7d\u8f66\u9500\u91cf\u6bd4\u4f8b": true,
            },
            show: true,
            padding: 50,
            itemGap: 10,
            itemWidth: 25,
            itemHeight: 14,
        },
    ],
    tooltip: {
        show: true,
        trigger: "axis",
        triggerOn: "mousemove|click",
        axisPointer: {
            type: "cross",
        },
        showContent: true,
        alwaysShowContent: false,
        showDelay: 0,
        hideDelay: 100,
        textStyle: {
            fontSize: 14,
        },
        borderWidth: 0,
        padding: 5,
    },
    xAxis: [
        {
            show: true,
            scale: false,
            nameLocation: "end",
            nameGap: 15,
            gridIndex: 0,
            inverse: false,
            offset: 0,
            splitNumber: 5,
            minInterval: 0,
            splitLine: {
                show: false,
                lineStyle: {
                    show: true,
                    width: 1,
                    opacity: 1,
                    curveness: 0,
                    type: "solid",
                },
            },
            data: [
                "2018",
                "2019",
                "2020",
                "2021",
                "2022",
                "2023",
                "2024",
                "2025",
            ],
        },
    ],
    yAxis: [
        {
            show: true,
            scale: false,
            nameLocation: "end",
            nameGap: 15,
            gridIndex: 0,
            inverse: false,
            offset: 0,
            splitNumber: 5,
            minInterval: 0,
            splitLine: {
                show: false,
                lineStyle: {
                    show: true,
                    width: 1,
                    opacity: 1,
                    curveness: 0,
                    type: "solid",
                },
            },
        },
        {
            type: "value",
            name: "\u9500\u91cf\uff08\u4e07\u8f86\uff09",
            show: true,
            scale: false,
            nameLocation: "end",
            nameGap: 15,
            gridIndex: 0,
            axisLine: {
                show: true,
                onZero: true,
                onZeroAxisIndex: 0,
                lineStyle: {
                    show: true,
                    width: 1,
                    opacity: 1,
                    curveness: 0,
                    type: "solid",
                    color: "black",
                },
            },
            axisLabel: {
                show: true,
                position: "top",
                margin: 8,
                formatter: "{value}",
            },
            inverse: false,
            position: "left",
            offset: 0,
            splitNumber: 5,
            min: 0,
            max: 600,
            minInterval: 0,
            splitLine: {
                show: false,
                lineStyle: {
                    show: true,
                    width: 1,
                    opacity: 1,
                    curveness: 0,
                    type: "solid",
                },
            },
        },
        {
            type: "value",
            name: "\u767e\u5206\u6bd4",
            show: true,
            scale: false,
            nameLocation: "end",
            nameGap: 15,
            gridIndex: 0,
            axisLine: {
                show: true,
                onZero: true,
                onZeroAxisIndex: 0,
                lineStyle: {
                    show: true,
                    width: 1,
                    opacity: 1,
                    curveness: 0,
                    type: "solid",
                    color: "#d14a61",
                },
            },
            axisLabel: {
                show: true,
                position: "top",
                margin: 8,
                formatter: "{value} %",
            },
            inverse: false,
            position: "right",
            offset: 0,
            splitNumber: 5,
            min: 0,
            max: 20,
            minInterval: 0,
            splitLine: {
                show: true,
                lineStyle: {
                    show: true,
                    width: 1,
                    opacity: 1,
                    curveness: 0,
                    type: "solid",
                },
            },
        },
    ],
    title: [
        {
            text: "新能源汽车销量及占比",
            x: "center",
            y: "top",
            textStyle: {
                fontSize: 30,
                color: "black",
                itemGap: 10,
            },
        },
    ],
};
chart_chart14.setOption(
    option_chart14
>>>>>>> acc4185 (third commit)
);